Repository emberjs/ember-render-modifiers, pull requests merged in 2021-10, with the labels that each got.

#44 Use ember-auto-import 2
  package.json
  yarn.lock
Labels: internal

#42 Update manager capabilities to 3.22 to fix deprecation in Ember 3.26+
  addon/modifiers/did-insert.js
  addon/modifiers/did-update.js
  addon/modifiers/will-destroy.js
  package.json
  yarn.lock
Labels: enhancement

#43 Fix deprecations in tests
  tests/integration/modifiers/will-destroy-test.js
  tests/test-helper.js
Labels: internal

#46 Update Ember to v3.28.0, drop node 10 support
  .eslintrc.js
  README.md
  ember-cli-build.js
  package.json
  tests/dummy/config/ember-cli-update.json
  yarn.lock
Labels: breaking
